name: 'run-tests'
on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        branches:
            - main
            - 'releases/*'
        paths-ignore:
            - '**.md'

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - run: echo $ENV_FILE | base64 -d > .env
              env:
                  ENV_FILE: ${{ secrets.ENV_FILE }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm test
