name: Testspace
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Function name'
        required: true
      payload:
        description: 'Function input-payload'
        required: true
      context:
        description: 'Function execution-context'
        required: true
env:
  IN_NAME: ${{ github.event.inputs.name }}
  IN_PAYLOAD: ${{ github.event.inputs.payload }}
  IN_CONTEXT: ${{ github.event.inputs.context }}
jobs:
  fixture:
    if: github.event.inputs.name == 'fixture'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Call Script implementing setup fixture
        run: node ./.github/workflows/handler.js
